[INCLUDES]
before = common.conf

[Definition]

_daemon = lemonldap\-ng

failregex = ^\s*%(__prefix_line)s\s*Lemonldap::NG : .* was not found in LDAP directory \(<HOST>\)\s*$
            ^\s*%(__prefix_line)s\s*Lemonldap::NG : Bad password for .* \(<HOST>\)\s*$

ignoreregex =
