[INCLUDES]
before = common.conf

[Definition]

_daemon = (?:s|u)?qpsmtpd(?:-forkserver)?

failregex = ^%(__prefix_line)s\s*\d+\s*logging::logterse plugin \(deny\): ` <HOST>\s*.*90\d.*msg denied before queued$
            ^%(__prefix_line)s\s*\d+\s*\(deny\) logging::logterse: ` <HOST>\s*.*90\d.*msg denied before queued$

ignoreregex = logters.*greylisting.*90.*temporarily denied
