# Fail2Ban filter for Smanager attempted bypasses

[Definition]
#[Mon Nov  9 20:33:34 2020] [info] Login FAILED: mab	192.168.0.11

failregex = ^\[.*\] \[info\] Login FAILED: .*\t<HOST>$

ignoreregex = ^\[.*\] \[debug\] .*$
ignoreregex = ^\[.*\] \[info\] Login succeeded: .*$

datepattern = {^LN-BEG}

