
[Definition]

actionstart =
actionstop =
actioncheck =
actionban = /sbin/e-smith/smeserver-fail2ban --host=<ip> --proto=<protocol> --port=<port> --bantime=<bantime>
actionunban = /sbin/e-smith/smeserver-fail2ban --host=<ip> --unban --proto=<protocol> --port=<port>

[Init]
protocol = undef
port = undef
bantime = undef
